# Generated by Django 4.2.7 on 2026-02-16 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertise_address', models.CharField(default='2492 Centennial NW, Acworth, GA, 30102', max_length=255)),
                ('advertise_phone', models.CharField(default='(678) 324-1251 (Toll-free)', max_length=50)),
                ('advertise_email', models.EmailField(default='advertise@example.com', max_length=254)),
                ('advertise_hours', models.CharField(default='Monday to Saturday, 9:30 am to 6:00 pm', max_length=100)),
                ('general_address', models.CharField(default='750 Sing Sing Rd, Horseheads, NY, 14845', max_length=255)),
                ('general_phone', models.CharField(default='469-537-2410 (Toll-free)', max_length=50)),
                ('general_email', models.EmailField(default='contact@example.com', max_length=254)),
                ('general_hours', models.CharField(default='Monday to Saturday, 9:00 am to 5:30 pm', max_length=100)),
                ('map_embed_url', models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d193595.15830869428!2d-74.119763973046!3d40.69766374874431!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sin!4v1698912345678!5m2!1sen!2sin')),
                ('enable_recaptcha', models.BooleanField(default=False)),
                ('recaptcha_site_key', models.CharField(blank=True, max_length=100, null=True)),
                ('recaptcha_secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('send_auto_reply', models.BooleanField(default=True)),
                ('auto_reply_subject', models.CharField(default='Thank you for contacting us', max_length=200)),
                ('auto_reply_message', models.TextField(default='Thank you for reaching out. We have received your message and will get back to you soon.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('advertise', 'Advertising / Sponsorship'), ('support', 'Technical Support'), ('feedback', 'Feedback / Suggestion'), ('other', 'Other')], default='general', max_length=20)),
                ('custom_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
