# Generated by Django 4.2.7 on 2026-02-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('primary', 'Primary'), ('danger', 'Danger'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
